name: "Upload Markdown to Confluence"
description: "Sync GitHub docs to Confluence"
author: "William Bruce"

inputs:
  root_page_id:
    description: "Parent page ID"
    required: false
  root_dir:
    description: "Directory containing markdown"
    required: false
    default: "."
  space:
    description: "Confluence space key"
    required: false

runs:
  using: docker
  image: Dockerfile
  env:
    ROOT_PAGE_ID: ${{ inputs.root_page_id }}
    ROOT_DIR: ${{ inputs.root_dir }}
    SPACE: ${{ inputs.space }}
