name: Upload Markdown to Confluence

on:
  workflow_call:
    inputs:
      CONFLUENCE_URL:
        required: true
        type: string
      CONFLUENCE_EMAIL:
        required: true
        type: string
      ROOT_PARENT_PAGE_ID:
        description: "Optional parent page ID for Confluence"
        required: true
        type: string
      SPACE:
        description: "Space ID for Confluence"
        required: true
        type: string
      ROOT_DIR:
        description: "Root directory containing the markdown files"
        required: true
        type: string
        default: "."
    secrets:
      CONFLUENCE_API_TOKEN:
        required: true

jobs:
  MDtoConfluence:
    runs-on: vs-github-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Confluence Sync
        env:
          CONFLUENCE_URL: ${{ inputs.CONFLUENCE_URL }}
          CONFLUENCE_EMAIL: ${{ inputs.CONFLUENCE_EMAIL }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}

          ROOT_PARENT_PAGE_ID: ${{ inputs.ROOT_PARENT_PAGE_ID || vars.ROOT_PARENT_PAGE_ID || '' }}
          SPACE: ${{ inputs.SPACE || vars.SPACE }}

        run: |
          python3 ./upload_to_confluence.py \
            --root-page-id "${ROOT_PARENT_PAGE_ID}" \
            --root-dir . \
            --space  "${SPACE}"
